### ISSUE TITLE
[ENHANCEMENT]: Use nixosModules

### ISSUE THREAD

**Issue by DerDennisOP** [Athena-OS/athena-nix#13]
I would like to import this as a nixosModule to my existing Configuration.

**Comment by D3vil0p3r** [comment]
Try to use flakes

**Comment by DerDennisOP** [comment]
I'm using flakes. How do I use it with my existing configuration?

**Comment by D3vil0p3r** [comment]
U should integrate some expressions in configuration.nix file of Athena and put in your configuration file and importing all the structure (files and folders)

**Comment by DerDennisOP** [comment]
![image](https://github.com/user-attachments/assets/355705f5-9b55-49e6-8f9d-6cd60df831e4)
I have a many servers, services and users in configuration.nix. Changing the entire structure is too much work. just copying the files from athena is also a lot of work. espacially if it has to be done over and over again for each individual person that is already using nix. A nixosModule would be the best way to add configutations to ones system. My entire configuration has 6181 lines of nix code, adapting to use athena (what I really would like), would be some much easier if I only would do athena = { enable = true; shell = "zsh"; ... }

**Comment by D3vil0p3r** [comment]
Mmh, currently my Nix exp does not involve NixOSModules. Can you try to create it?

**Comment by DerDennisOP** [comment]
I mean I can try. Also is there going to be hyperland? There is also this project: https://github.com/end-4/dots-hyprland

**Comment by D3vil0p3r** [comment]
I have a Hyprland theme to use. The problem is that it needs to write on files that in NixOS are intended to be read-only. If there is a simple dotfiles tested and working, I can implement in Athena Nix.

**Comment by DerDennisOP** [comment]
> I have a Hyprland theme to use. The problem is that it needs to write on files that in NixOS are intended to be read-only. If there is a simple dotfiles tested and working, I can implement in Athena Nix.

Whats the problem exactly. Can you link some code where you want to write?

**Comment by D3vil0p3r** [comment]
This is the env I would like to integrate: https://github.com/end-4/dots-hyprland

**Comment by DerDennisOP** [comment]
I can make 3 PRs by next week:
- clean up & refactor
- use of nixosModules + some better docs
- add Hyperland (maybe some config parts from here: https://github.com/end-4/CirnOS)

**Comment by DerDennisOP** [comment]
@D3vil0p3r can you review #16 and maybe you could try to add hyperland? It was already much work to refactor big parts of the code, and I'm still not done yet.

**Comment by D3vil0p3r** [comment]
It is long to review, but I see that you refactored the code for Athena Nix Flake in order to make it more flexible... But since you edited several default.nix files, are you tested if it still works in case a user uses `nixos-rebuild switch` with the `configuration.nix` file instead of flakes?

I tested it now by using the configuration.nix file and I get:
```
error: The option `athena-nix.homeManagerUser' is used but not defined.
```
If the proposal does not work both for `configuration.nix` and flakes, I cannot merge the related PR.

**Comment by DerDennisOP** [comment]
How have you tested it? Afaik it should work with both, I have tested it and it worked for me. The error you are describing occures, when athena-nix.homeManagerUser is not set. I'll put in defaults, so this error won't happen anymore. You can try again.

**Comment by D3vil0p3r** [comment]
> how have you tested it. Afaik it should work with both, I have tested it and it worked for me. The error you are describing occures, when athena-nix.homeManagerUser is not set. I'll put in defaults, so this error won't happen anymore.

I expected that error because in `configuration.nix` it should be set. By the way I just cloned your forked repository, I copied all files in `/etc/nixos` and I run `sudo nixos-rebuild switch`.

**Comment by D3vil0p3r** [comment]
Note that all the changes done by the users must be tweaked in only `configuration.nix` because this file is connected to the Athena installer.

**Comment by DerDennisOP** [comment]
Oh you are right. I haven't touched the configuration nix stuff. I can fix it really quick.

**Comment by DerDennisOP** [comment]
Ok, should hopefully be fixed. please test it once again.

**Comment by D3vil0p3r** [comment]
Getting:
```
       error: attribute 'username' missing

       at /etc/nixos/modules/dev/tmux/default.nix:14:26:

           13|   config = lib.mkIf config.athena-nix.baseConfiguration {
           14|     home-manager.users.${config.athena-nix.username} = { pkgs, ... }: {
             |                          ^
           15|       programs.tmux = {
```

**Comment by DerDennisOP** [comment]
I'm sorry that I have to use you as a current test bench, should be fixed. Do you want the configuration option named athena-nix or just athena?

**Comment by D3vil0p3r** [comment]
Just athena

**Comment by DerDennisOP** [comment]
changed.

**Comment by D3vil0p3r** [comment]
I get:
```
error: The option `home-manager.users.athena.home.stateVersion' is used but not defined.
```

**Comment by DerDennisOP** [comment]
yup, also this is fixed. I got confused by the old config smh.

**Comment by D3vil0p3r** [comment]
Another error:
```
       at /etc/nixos/modules/misc/nist-feed/default.nix:4:9:

            3| let
            4|   cfg = config.services.nist-feed;
             |         ^
            5|   nistFeedPkg = pkgs.callPackage ../../../pkgs/nist-feed/package.nix { };
```
Can you please test on your clean NixOS machine? Otherwise I stuck at testing it several times and getting errors.

**Comment by DerDennisOP** [comment]
I dont really have a system that I can use rn, that the problem.

**Comment by D3vil0p3r** [comment]
Did you refactor all those files without testing in a system?

**Comment by DerDennisOP** [comment]
I included it in my system config. But I can't just do switching, because I don't even have an /etc/nixos/hardware-configuration.nix. I would need some clean system by any possiblity.

**Comment by D3vil0p3r** [comment]
Try to set up a VM

**Comment by DerDennisOP** [comment]
I coudn't get the VM to setup, but I figured out a way to test it.

**Comment by DerDennisOP** [comment]
WELL, that was the last error anyway xD. Please tell me if you encounter any runtime errors.

**Comment by D3vil0p3r** [comment]
Ok it seems to work. I need just to test it by the installer and cyber roles. My question: why did you propose this refactoring instead of the previous structure? What are the advantages?

**Comment by DerDennisOP** [comment]
now everything is a module. making it less a configurations, rather more a package that you can universally through at any existing configuration. I can't really explain what all the benefits of modules are, but the main advantage is that you can now change your configuration without touching this git repo / or cloneing it.

![image](https://github.com/user-attachments/assets/17cc29ed-512d-48a4-82ff-fae6c4a5b850)
you basically can add it in flake inputs like "home-manager", and you have all the configuration needed to use athenaos.

**Comment by DerDennisOP** [comment]
> Ok it seems to work. I need just to test it by the installer and cyber roles. My question: why did you propose this refactoring instead of the previous structure? What are the advantages?

@D3vil0p3r any updates?

**Comment by D3vil0p3r** [comment]
Hey. I need to find free time to check it in deep and merge the PR. In these weeks will be hard to find time, but I try to get some dedicated moments for it.

**Comment by DerDennisOP** [comment]
> @D3vil0p3r can you review #16 and maybe you could try to add hyperland? It was already much work to refactor big parts of the code, and I'm still not done yet.

so, have you any suggestions on using hyperland. You told me that you wanned to include an env from end-4, I didn't quite get the problem in doing it. I really enjoy the look and style of this (https://athenaos.org/en/configuration/hyperland), I'm already using hyperland, but coudn't get ags to working.

**Comment by D3vil0p3r** [comment]
> > @D3vil0p3r can you review #16 and maybe you could try to add hyperland? It was already much work to refactor big parts of the code, and I'm still not done yet.
> 
> so, have you any suggestions on using hyperland. You told me that you wanned to include an env from end-4

I did some attempts time ago but it could not be possible because of immutability of NixOS env.

**Comment by DerDennisOP** [comment]
> > > @D3vil0p3r can you review #16 and maybe you could try to add hyperland? It was already much work to refactor big parts of the code, and I'm still not done yet.
> > 
> > 
> > so, have you any suggestions on using hyperland. You told me that you wanned to include an env from end-4
> 
> I did some attempts time ago but it could not be possible because of immutability of NixOS env.

usually this shoudn't be any problem at all. Maybe you could try again, and show me the exact errors you got, then I might be able to help you.

**Comment by D3vil0p3r** [comment]
The problem is that one component (I don't remember if ags) attempts to write on its installation folder (that in NixOS is under /nix/store, so read-only).

**Comment by DerDennisOP** [comment]
> The problem is that one component (I don't remember if ags) attempts to write on its installation folder (that in NixOS is under /nix/store, so read-only).

Haven't you keeped the configurations files somewhere? So we can try to fix those errors? Sometimes programs try to write into their installation folder, but usually this can be fixed.

**Comment by AkechiShiro** [comment]
Is this issue still relevant ? @DerDennisOP

**Comment by DerDennisOP** [comment]
> Is this issue still relevant ? @DerDennisOP

I would like to have hyprland integration, but we can make a new issue for this.

**Comment by D3vil0p3r** [comment]
Yes. Let's open a dedicated issue ticket.

**Comment by gax1985** [comment]
I am in the same boat as OP, as I would like to use Athena-OS's applications, menu setup and its tools, but I wish to preserve my pre-existing NixOS flake configuration. I have pondered the present configuration file, and I noticed the following options : 

    {
      athena = {
        inherit bootloader terminal theme mainShell browser;
        enable = true;
        homeManagerUser = username;
        **baseConfiguration = true;**
        ** baseSoftware = true; **
        **baseLocale = true;**
        desktopManager = desktop;
        displayManager = dmanager;
      };
    }


Would setting **baseConfiguration = false** do the trick? or would the **baseLocale=false** would be more appropriate? Thank you for your hard work folks! I love Athena!

**Comment by DerDennisOP** [comment]
@gax1985 If you want you can ask the Maintainer if he wants a PR (to improve nixos modules even more) on this. As you can see I added nixos modules and refactored basically everything, so setting baseConfiguration = false would probably give you the result you wanted.

**Comment by gax1985** [comment]
> @gax1985 If you want you can ask the Maintainer if he wants a PR (to improve nixos modules even more) on this. As you can see I added nixos modules and refactored basically everything, so setting baseConfiguration = false would probably give you the result you wanted.

I would be happy to work with you guys on making a Flakes module that can be imported into a pre-existing flake setup. I imagine it to be like this:

athena-nix.nixosModules.minimalConfiguration

Or :

athena-nix.nixosModules.fullConfiguration

After years of distrohopping, I found in Nix/NixOS a home. I appreciate your guidance, and I will be trying out this option. I have made a *specialisation* module before, where you can select Athena-Nix on the systemd/GRUB boot menu, due to the conflicts between the previously-selected options on my part, such as having my own home-manager setup or sporting a different desktop environment like Mate or Cinnamon that uses GTK files and libraries. 

Thank you!

**Comment by gax1985** [comment]
> [@gax1985](https://github.com/gax1985) If you want you can ask the Maintainer if he wants a PR (to improve nixos modules even more) on this. As you can see I added nixos modules and refactored basically everything, so setting baseConfiguration = false would probably give you the result you wanted.




I have tried disabling the baseConfiguration option. I use Stylix, so after changing the option from true to false, I got a conflict during nixos-rebuild  pertaining to the gtk theme name, and after finding the file containing the option in the athena-nix folder structure, and adding lib.mkForce before the option, there was another conflict with the GTK theme's package name option. Thus, if I have understood your recommendation correctly ; disabling the option should disable any home-manager-based configuration options, it does not appear to be the case, as it is trying to apply the styles in the athena-nix configuration.nix file. 

I appreciate your hard work, and your guidance on this matter. I was thinking of a few options to take to apply athena-nix to my pre-existing setup : 

1. Track down all the default.nix files in the athena-nix project's folder structure, and importing default.nix files that do not involve home-manager configurations (so Stylix can happily make any appearance-based actions it needs to take, such as applying themes, etc). Furthermore, I believe that in order to install all the applications based in the project's different roles ( as in the *roles* folder) it would probably require creating new .nix files that indicate that the packages would be installed as user packages.

2. Add the athena-nix project as a *specialisation*, which I have done before. This way, I can import any of my own .nix files that contain the options that do not pertain to desktop environment configuration in the specialisation, and simply add .nix files pertaining to the extra applications I would like to add to the system and so on. 


Thanks again! I am learning a lot from you and other contributors to this project, specifically pertaining to Home-Manager configurations/modules!

**Comment by DerDennisOP** [comment]
> > [@gax1985](https://github.com/gax1985) If you want you can ask the Maintainer if he wants a PR (to improve nixos modules even more) on this. As you can see I added nixos modules and refactored basically everything, so setting baseConfiguration = false would probably give you the result you wanted.
> 
> I have tried disabling the baseConfiguration option. I use Stylix, so after changing the option from true to false, I got a conflict during nixos-rebuild pertaining to the gtk theme name, and after finding the file containing the option in the athena-nix folder structure, and adding lib.mkForce before the option, there was another conflict with the GTK theme's package name option. Thus, if I have understood your recommendation correctly ; disabling the option should disable any home-manager-based configuration options, it does not appear to be the case, as it is trying to apply the styles in the athena-nix configuration.nix file.
> 
> I appreciate your hard work, and your guidance on this matter. I was thinking of a few options to take to apply athena-nix to my pre-existing setup :
> 
>     1. Track down all the default.nix files in the athena-nix project's folder structure, and importing default.nix files that do not involve home-manager configurations (so Stylix can happily make any appearance-based actions it needs to take, such as applying themes, etc). Furthermore, I believe that in order to install all the applications based in the project's different roles ( as in the _roles_ folder) it would probably require creating new .nix files that indicate that the packages would be installed as user packages.
> 
>     2. Add the athena-nix project as a _specialisation_, which I have done before. This way, I can import any of my own .nix files that contain the options that do not pertain to desktop environment configuration in the specialisation, and simply add .nix files pertaining to the extra applications I would like to add to the system and so on.
> 
> 
> Thanks again! I am learning a lot from you and other contributors to this project, specifically pertaining to Home-Manager configurations/modules!

I think baseConfiguration should keep the HomeManager Configurations, but not enable any configuration options regarding your general pc settings: e.g. language, keyboard layout, etc.

What do you mean with "add the athena-nix project as a specialisation"? Athena-nix should be added to you configuration as a nix module.

I haven't used Stylix yet, but maybe we need a config option for that e.g.: "modifyColortheme". I don't understand what you mean with "in order to install all the applications [...] require creating new .nix files", could you elaborate on this please?

**Comment by gax1985** [comment]
> What do you mean with "add the athena-nix project as a specialisation"? Athena-nix should be added to you configuration as a nix module.

I mean it in the following way : 

My current NixOS configuration/flake file/folder structure : 

./flake.nix
./flake.nix.bak
./home-manager
./home-manager/Macbook
./home-manager/Macbook/Macbook.nix
./home-manager/plasma-home.nix
./home-manager/wsl.nix
./Hosts
./Hosts/MacbookPro-NixOS
./Hosts/MacbookPro-NixOS/configuration.nix
./justfile
./Modules
./Modules/Appearance
./Modules/Appearance/Fonts.nix
./Modules/Appearance/Terminal.nix
./Modules/Appearance/Themes+Icons.nix
./Modules/Applications
./Modules/Applications/Common
./Modules/Applications/Common/Applications.nix
./Modules/Applications/Common/Applications-SystemPackages.nix
./Modules/Applications/Darwin
./Modules/Applications/Darwin/Applications.nix
./Modules/Applications/GNOME
./Modules/Applications/GNOME/Extensions.nix
./Modules/Applications/KDE
./Modules/Applications/KDE/Applications-KDE.nix
./Modules/Applications/KDE/Plasma-Extensions.nix
./Modules/Applications/Surface
./Modules/Applications/Surface/Applications.nix
./Modules/Bootloader
./Modules/Bootloader/GRUB-Boot.nix
./Modules/Bootloader/SYSTEMD-Boot.nix
./Modules/common-modules-1.nix
./Modules/common-modules-2.nix
./Modules/common-modules-3.nix
./Modules/common-modules copy.nix
./Modules/common-modules.nix
./Modules/Desktop-Environments
./Modules/Desktop-Environments/Cinnamon.nix
./Modules/Desktop-Environments/Cosmic.nix
./Modules/Desktop-Environments/Gnome.nix
./Modules/Desktop-Environments/Hyprland.nix
./Modules/Desktop-Environments/Maui.nix
./Modules/Desktop-Environments/Pantheon.nix
./Modules/Desktop-Environments/Plasma.nix
./Modules/Options
./Modules/Options/AllHardwareAllFirmware.nix
./Modules/Options/Android.nix
./Modules/Options/Autologin.nix
./Modules/Options/builder-recepient.nix
./Modules/Options/custom-binary-cache.nix
./Modules/Options/Darwin-Emulation.nix
./Modules/Options/Darwin.nix
./Modules/Options/External-Drives.nix
./Modules/Options/Flatpak.nix
./Modules/Options/Gaming.nix
./Modules/Options/Gaming.nix.bak
./Modules/Options/Git.nix
./Modules/Options/Network-Bridge.nix
./Modules/Options/nix.conf.nix
./Modules/Options/Nix.nix
./Modules/Options/NixOS-as-Guest.nix
./Modules/Options/NTFS.nix
./Modules/Options/NVIDIA-New.nix
./Modules/Options/NVIDIA.nix
./Modules/Options/NVME.nix
./Modules/Options/Oh-My-Posh.nix
./Modules/Options/README.md
./Modules/Options/remote-builder.nix
./Modules/Options/ROCm.nix
./Modules/Options/RTC.nix
./Modules/Options/SteamDeck.nix
./Modules/Options/Substitutors.nix
./Modules/Options/Surface.nix
./Modules/Options/user-settings.nix
./Modules/Options/Waydroid.nix
./Modules/Options/WSL.nix
./Modules/Services
./Modules/Services/AI-ComfyUI-CUDA.nix
./Modules/Services/AI-ComfyUI-ROCm.nix
./Modules/Services/AI-LocalAI-CUDA.nix
./Modules/Services/AI-LocalAI-HIPBLAS.nix
./Modules/Services/AI-MidoriAI-ALL.nix
./Modules/Services/AI-MidoriAI-CUDA.nix
./Modules/Services/AI-Ollama-CUDA.nix
./Modules/Services/AI-Ollama-ROCm.nix
./Modules/Services/Cockpit.nix
./Modules/Services/Corectl.nix
./Modules/Services/Docker.nix
./Modules/Services/gtfy.nix
./Modules/Services/Headscale.nix
./Modules/Services/Jellyfin.nix
./Modules/Services/Nextcloud.nix
./Modules/Services/ntfy.nix
./Modules/Services/OpenRGB.nix
./Modules/Services/Opensnitch.nix
./Modules/Services/PiHole.nix
./Modules/Services/Plex.nix
./Modules/Services/Podman.nix
./Modules/Services/Services.nix
./Modules/Services/Sniffnet.nix
./Modules/Services/sunshine.nix
./Modules/Services/Syncthing.nix
./Modules/Services/Tailscale.nix
./Modules/Services/Technitium.nix
./Modules/Services/Thermal.nix
./Modules/Services/VSCode-Remote.nix
./Modules/Services/Wakapi.nix
./Modules/Services/WatchYourLan.nix
./Modules/Specialisations
./Modules/Specialisations/AthenaOS.nix
./Modules/Specialisations/Proxmox.nix
./Modules/Stylix
./Modules/Stylix/Base16-Themes-List.desktop
./Modules/Stylix/Catppuccin
./Modules/Stylix/Catppuccin/Day.nix
./Modules/Stylix/Catppuccin/Night.nix
./Modules/Stylix/Dracula
./Modules/Stylix/Dracula/Day.nix
./Modules/Stylix/Dracula/Night.nix
./Modules/Stylix/Fonts.nix
./Modules/Stylix/Gruvbox
./Modules/Stylix/Gruvbox/Day.nix
./Modules/Stylix/Gruvbox/Night.nix
./Modules/Stylix/Nord
./Modules/Stylix/Nord/Day.nix
./Modules/Stylix/Nord/Night.nix
./Modules/System-Configurations
./Modules/System-Configurations/Desktop.nix
./Modules/System-Configurations/Laptop.nix
./Modules/System-Configurations/SteamDeck.nix
./Modules/System-Configurations/Surface.nix
./Modules/System-Configurations/VM.nix
./Modules/Virtualization
./Modules/Virtualization/Libvirtd.nix
./Modules/Virtualization/Virtualbox.nix
./Modules/Virtualization/Virtualization.nix
./Modules/Virtualization/VMWARE.nix


As you can see, I have a lot of .nix files. What I do is add the .nix files as imports for each system's configuration in the flake.nix file. Thus, I have the athena-nix project folder in there as well, and I simply add the athena-nix/configuration.nix file as an import (after making sure I disable all .nix files containing Home-Manager options, or any other imported modules that would work with the desktop manager's appearance like Stylix). Since the athena-nix project has its own styling for the desktop manager, I made a separate Athena-Nix.nix file that declares the imported athena-nix/configuration.nix file as an import : 

#### [Modules/Specialisations/AthenaOS.nix]
``
{ config, pkgs, lib, ... }:
 {

  specialisation.AthenaOS.inheritParentConfig = false; # ... to avoid any conflicts pertaining to the desktop-manager/home-manager settings  
  
  specialisation.AthenaOS.configuration = 
  {
  users.users.username.isNormalUser = true;
  users.users.username.group = "username";
           users.groups.username = {};


  imports = [./athena-nix/nixos/configuration.nix
	     ./Services/AI.nix
             ./Applications/Applications.nix
	     ./Applications/Applications-SystemPackages.nix
		];
``

This has worked previously for me, as it allows me to have multiple options at boot. My plan is to have specialisations for Jovian-NixOS, Athena-Nix and my normal config. Nonetheless, it will be far more favorable, in terms of readiness, to have all the athena-nix menu configurations and all cybersecurity tools available at all times.  

In terms of calling the athena-nix configuration file, my current system's configuration in the flake.nix is currently set up in this fashion : 

``
 nixosConfigurations.SURFACE-ATHENA = nixpkgs.lib.nixosSystem {
        #self.nixosSystem {
        system = "x86_64-linux";

 
            modules = [

          /etc/nixos/hardware-configuration.nix
           /etc/nixos/configuration.nix --> athena-nix's configuration.nix
           ./Modules/Options/Surface.nix
           ./Modules/Options/NVME.nix
           ./Modules/Options/Android.nix
           ./Modules/Options/Waydroid.nix
...
``

Thanks again!

**Comment by DerDennisOP** [comment]
@gax1985 Why are you not using athena as a flake input? https://nixos-and-flakes.thiscute.world/nixos-with-flakes/nixos-flake-and-module-system

**Comment by gax1985** [comment]
> @gax1985 Why are you not using athena as a flake input? https://nixos-and-flakes.thiscute.world/nixos-with-flakes/nixos-flake-and-module-system

I apologize, but I was not aware of a methodology involving an Athena-Nix flake input? I have other projects added as flake inputs in my flake file. I have examined the Athena documentation previously. If it has slipped by me, can you share the link/documentation that outlines the method pertaining to athena-nix ?
